package forward;
import com.ftn.sbnz.model.models.NetworkService;
import com.ftn.sbnz.model.models.Device;
import com.ftn.sbnz.model.models.Vulnerability;
import com.ftn.sbnz.model.models.Recommendation;
import com.ftn.sbnz.model.models.Severity;
import com.ftn.sbnz.model.events.Alert;

//Telnet servis
rule "F1: Telnet insecure"
when
    $s : NetworkService( name == "telnet" || port == 23, $dev : device )
then
    insert( new Vulnerability($dev, "TELNET_INSECURE", Severity.HIGH, "Telnet is insecure; disable.") );
end

rule "F2: Recommend close port"
when
    $v : Vulnerability( code == "TELNET_INSECURE", $dev : device )
then
    insert( new Recommendation("Close port 23 / remove telnet on device: " + $dev, "Insecure networkService"));
end

rule "F3: Raise network alarm when many telnet vulns"
when
    Number( intValue >= 3 ) from accumulate (
        Vulnerability( code == "TELNET_INSECURE", $dev : device ),
        count($dev.getId())
    )
then
    insert( new Alert("ALARM_TELNET_WIDESPREAD", Severity.HIGH, "3+ devices with Telnet") );
end

//B: Izracun rizika
rule "F4: HTTP without TLS"
when
    $s : NetworkService( name == "http", port == 80, $dev : device )
then
    insert( new Vulnerability($dev, "TELNET_INSECURE", Severity.MID, "Telnet is insecure; disable.") );
end

rule "F5: Outdated SSH"
when
    $s : NetworkService( name == "ssh", version == "2.4.56", $dev : device )
then
    insert( new Vulnerability($dev, "SSH_OLD", Severity.HIGH, "Upgrade OpenSSH >= 8.9") );
end

rule "F6: Risk score and isolate"
when
    $d : Device( $id : id )
    $score : Number( intValue >= 1 ) from accumulate(Vulnerability( device == $d, $sev : severity ),
    sum( $sev == Severity.HIGH ? 3 : 2 ))
then
    insert( new Recommendation("Isolate device from external network" + $d, "Risk score >= 5"));

end